### DISCUSSION TITLE
Example Graphs from my Heatpump

### DISCUSSION THREAD

**Discussion by cbrosius** [cbrosius/luxtronik_v1#20] [Show and tell]
<img width="374" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/75a4120c-c527-4bb2-b9d9-8e0a5e6ce7ce">

<img width="373" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/9ce69a0d-d8f3-4835-b0f4-b917e28614a0">

<img width="373" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/bfba96d2-0777-42f7-ba43-6d3131b451f4">

**Comment by optimismus** [comment]
That look quite cool - much better than mine. May be you create an folder in the repository with the yaml-Code of the dashboards?!

**Reply by cbrosius** [reply]
There is nothing special about the dashboards. Just plain HomeAssistant-Basic HistoryGraph-Components.
<img width="738" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/1292067f-518c-4c38-8416-d13f3ec06a74">
<img width="816" alt="image" src="https://github.com/CBrosius/luxtronik_v1/assets/23188584/8d208e80-5ebd-47a0-9d11-685518647e32">

**Reply by optimismus** [reply]
But how did you translate the number Betriebszustand to a word? and the temperature curves ... 
Dashboard examples as yaml was just an idea.

**Reply by cbrosius** [reply]
You are correct, I have a template-sensor for WP_Betriebszustand in my configuration.yaml I did not recognize 
```
  - platform: template
    sensors:
      wp_betriebszustand:
        friendly_name: "Status Wärmepumpe"
        unique_id: TZ_WP_Betriebszustand
        value_template: >-
          {% set mapper =  {
            '0' : 'Heizen',
            '1' : 'Warmwasser',
            '3' : 'EVU Sperre',
            '5' : 'Bereitschaft',
            '10': '10',
            '12': '12',
            '15': '15',
            '1700': '1700' } %}
          {% set state =  states('sensor.luxtronik_v1_esp32_wp_status_betriebszustand') %}
          {{ mapper[state] if state in mapper else 'unbekannt' }}

```

**Reply by cbrosius** [reply]
This is the YAML for the graphs:
```
type: history-graph
entities:
  - entity: sensor.luxtronik_v1_esp32_wp_temp_aussentemperatur
    name: Außentemperatur
  - entity: sensor.luxtronik_v1_esp32_wp_temp_heizkreis_ist_vorlauftemperatur
    name: Heizkreis-Vorlauf
  - entity: sensor.luxtronik_v1_esp32_wp_temp_heizkreis_ist_ruecklauftemperatur
    name: Heizkreis-Rücklauf
  - entity: sensor.luxtronik_v1_esp32_wp_temp_brauchwarmwasser_ist_temperatur
    name: Brauchwasser_IST
  - entity: sensor.luxtronik_v1_esp32_wp_temp_brauchwarmwasser_soll_temperatur
    name: Brauchwasser_SOLL
  - entity: sensor.luxtronik_v1_esp32_wp_temp_waermequellen_eintrittstemperatur
    name: Wärmequelle-Eintritt
  - entity: sensor.luxtronik_v1_esp32_wp_temp_waermequellen_austrittstemperatur
    name: Wärmequelle-Austritt
title: Wärmepumpen-Temperaturen
hours_to_show: 24
```
