### ISSUE TITLE
Config Ordner

### ISSUE THREAD

**Issue by approx3145** [cbrosius/luxtronik_v1#28]
Hallo 

Kann keinen config/esphome Ordner finden 

Es gibt nur einen esphome folder

**Comment by cbrosius** [comment]
Ja, das ist der korrekte Ordner. Da einfach die luxtronik_v1_sensor.h mit reinlegen.
Allerdings musst Du beachten, daß die aktuellste ESPHome-Version keine CustomComponents mehr unterstützt.
Du brauchst also eine Version vor 2025 damit erfolgreich kompiliert werden kann.

Ab 2025 werden nur noch ExternalComponents unterstützt, das hab ich mir schonmal angesehen, konnte es aber auf die Schnelle nicht problemlos umprogrammieren. Da muss ich in Ruhe nochmal ran. Ist aber definitiv auf meiner ToDo-Liste.

Gruß,
Christian...

**Comment by approx3145** [comment]
wie kann ich die serielle Verbindung kontrollieren? Sehe da keine Angaben?

[13:03:15][C][uart.arduino_esp32:151]: UART Bus 0:
[13:03:15][C][uart.arduino_esp32:152]:   TX Pin: GPIO17
[13:03:15][C][uart.arduino_esp32:153]:   RX Pin: GPIO16
[13:03:15][C][uart.arduino_esp32:155]:   RX Buffer Size: 256
[13:03:15][C][uart.arduino_esp32:157]:   Baud Rate: 57600 baud
[13:03:15][C][uart.arduino_esp32:158]:   Data Bits: 8
[13:03:15][C][uart.arduino_esp32:159]:   Parity: NONE
[13:03:15][C][uart.arduino_esp32:160]:   Stop bits: 1
[13:03:15][C][uptime.sensor:033]: Uptime Sensor 'Uptime Sensor'
[13:03:15][C][uptime.sensor:033]:   Device Class: 'duration'
[13:03:15][C][uptime.sensor:033]:   State Class: 'total_increasing'
[13:03:15][C][uptime.sensor:033]:   Unit of Measurement: 's'
[13:03:15][C][uptime.sensor:033]:   Accuracy Decimals: 0
[13:03:15][C][uptime.sensor:033]:   Icon: 'mdi:timer-outline'
[13:03:15][C][uptime.sensor:034]:   Type: Seconds
[13:03:15][C][status:034]: Status Binary Sensor 'luxtronik-v1-esp32'
[13:03:15][C][status:034]:   Device Class: 'connectivity'
[13:03:15][C][web_server:153]: Web Server:
[13:03:15][C][web_server:154]:   Address: 192.168.10.12:80
[13:03:15][C][mdns:116]: mDNS:
[13:03:15][C][mdns:117]:   Hostname: luxtronik-v1-esp32
[13:03:15][C][esphome.ota:073]: Over-The-Air updates:
[13:03:15][C][esphome.ota:074]:   Address: 192.168.10.12:3232
[13:03:15][C][esphome.ota:075]:   Version: 2
[13:03:15][C][safe_mode:018]: Safe Mode:
[13:03:15][C][safe_mode:020]:   Boot considered successful after 60 seconds
[13:03:15][C][safe_mode:021]:   Invoke after 10 boot attempts
[13:03:15][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[13:03:15][C][api:140]: API Server:
[13:03:15][C][api:141]:   Address: 192.168.10.12:6053
[13:03:15][C][api:145]:   Using noise encryption: NO
[13:03:15][C][wifi_signal.sensor:010]: WiFi Signal 'WiFi Signal Sensor'
[13:03:15][C][wifi_signal.sensor:010]:   Device Class: 'signal_strength'
[13:03:15][C][wifi_signal.sensor:010]:   State Class: 'measurement'
[13:03:15][C][wifi_signal.sensor:010]:   Unit of Measurement: 'dBm'
[13:03:15][C][wifi_signal.sensor:010]:   Accuracy Decimals: 0
[13:03:15][D][sensor:094]: 'WiFi Signal Sensor': Sending state -42.00000 dBm with 0 decimals of accuracy

**Comment by cbrosius** [comment]
die serielle Verbindung wird in der YAML konfiguriert.

```
uart:
  baud_rate: 57600
  rx_pin: GPIO16
  tx_pin: GPIO17
  # baud_rate (Required, int): The baud rate of the UART bus.
  # rx_pin (Optional, Pin): The pin to receive data on from the ESP’s perspective.
  # tx_pin (Optional, Pin): The pin to send data to from the ESP’s perspective.
  data_bits: 8
  #data_bits (Optional, int): The number of data bits used on the UART bus. Options: 5 to 8. Defaults to 8.
  #parity (Optional): The parity used on the UART bus. Options: NONE, EVEN, ODD. Defaults to NONE.
  parity: NONE
  #stop_bits (Optional, int): The number of stop bits to send. Options: 1, 2. Defaults to 1.
  stop_bits: 1
  # id (Optional, ID): Manually specify the ID for this UART hub if you need multiple UART hubs
  id: uart_bus
```
